spring.application.name=payment-service
app.instance-id=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/nexupay
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.flyway.enabled=true

logging.level.com.zaxxer.hikari=DEBUG
#for metric and actuator and health
management.endpoints.web.exposure.include=health,metrics
management.endpoint.metrics.access=unrestricted

#Hikari connection pool
spring.datasource.hikari.maximum-pool-size=20

#redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

#cache key
nexupay.security.cache-key=this-is-my-cache-key-for-authentication
#for redis cache TTL
nexupay.security.auth-cache-ttl=10m