CREATE TABLE merchant (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id VARCHAR(50) UNIQUE NOT NULL,
    business_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone VARCHAR(20),
    status VARCHAR(20) NOT NULL
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED')),
    webhook_url VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE api_credential (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credential_id VARCHAR(50) UNIQUE NOT NULL,
    merchant_id BIGINT NOT NULL,
    api_key VARCHAR(255) UNIQUE NOT NULL,
    secret_key_hash VARCHAR(255) NOT NULL,
    environment VARCHAR(20) NOT NULL
        CHECK (environment IN ('SANDBOX', 'PRODUCTION')),
    status VARCHAR(20) NOT NULL
        CHECK(status IN('ACTIVE','REVOKED')),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_api_credential_merchant
        FOREIGN KEY (merchant_id)
        REFERENCES merchant(id)
);

CREATE TABLE payment(

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id VARCHAR(50) UNIQUE NOT NULL,
    merchant_id BIGINT NOT NULL,
    merchant_order_id VARCHAR(50) NOT NULL,
    customer_name VARCHAR(255) NULL,
    customer_email VARCHAR(255) NULL,
    customer_phone VARCHAR(10) NULL,
    amount NUMERIC(19,2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    status VARCHAR(20) NOT NULL
        CHECK(status IN('CREATED','SUCCESS','FAILED','EXPIRED')),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_payment_merchant
        FOREIGN KEY (merchant_id)
        REFERENCES merchant(id),
    CONSTRAINT uk_payment_merchant_order
        UNIQUE(merchant_id,merchant_order_id)
);

CREATE TABLE payment_attempt(

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id VARCHAR(255) UNIQUE NOT NULL,
    payment_id BIGINT NOT NULL,
    attempt_number INT NOT NULL,
    status VARCHAR(20) NOT NULL
        CHECK(status IN('CREATED','SUCCESS','FAILED')),
    failure_reason VARCHAR(100),
    payment_method VARCHAR(20) NOT NULL
        CHECK (payment_method IN ('UPI','CARD','NET_BANKING','WALLET')),
    bank_reference_id VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_payment_attempt_payment
        FOREIGN KEY (payment_id)
        REFERENCES payment(id),
    CONSTRAINT uk_payment_attempt_number
            UNIQUE (payment_id, attempt_number)
);

CREATE TABLE payment_webhook(

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id VARCHAR(50) NOT NULL,
    webhook_url VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL
        CHECK(status IN('PENDING','SUCCESS','FAILED')),
    attempt_count INT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_payment_webhook_payment
            UNIQUE (payment_id)
);
