CREATE TABLE refund (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    refund_id VARCHAR(50) NOT NULL UNIQUE,

    payment_id VARCHAR(50) NOT NULL,

    merchant_refund_id VARCHAR(100) NOT NULL,

    amount NUMERIC(19,2) NOT NULL,

    currency VARCHAR(3) NOT NULL,

    status VARCHAR(20) NOT NULL
        CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED')),

    bank_reference_id VARCHAR(100),

    failure_reason VARCHAR(255),

    created_at TIMESTAMP NOT NULL,

    updated_at TIMESTAMP NOT NULL,

    CONSTRAINT uk_refund_merchant_refund
        UNIQUE (merchant_refund_id, payment_id)
);