CREATE TABLE bank_refund (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    refund_id VARCHAR(50) NOT NULL UNIQUE,

    payment_id VARCHAR(50) NOT NULL,

    amount NUMERIC(19, 2) NOT NULL,

    currency VARCHAR(3) NOT NULL,

    bank_reference_id VARCHAR(50) NOT NULL UNIQUE,

    status VARCHAR(20) NOT NULL,

    created_at TIMESTAMP NOT NULL,

    updated_at TIMESTAMP NOT NULL,

    CONSTRAINT chk_bank_refund_amount_positive
        CHECK (amount > 0),

    CONSTRAINT chk_bank_refund_status
        CHECK (status IN ('SUCCESS', 'FAILED'))
);