package com.nexupay.payment.common.enums;

public enum ErrorCode {
    VALIDATION_ERROR,
    MERCHANT_ALREADY_EXISTS,
    INVALID_API_CREDENTIALS,
    PAYMENT_DOES_NOT_EXIST,
    INVALID_PAYMENT_STATUS,
    MERCHANT_NOT_FOUND,
    PAYMENT_ATTEMPT_NOT_FOUND,
    PAYMENT_EXPIRED,
    PAYMENT_NOT_FOUND_BY_MERCHANT,
    REFUND_AMOUNT_EXCEEDS,
    PAYMENT_NOT_ELIGIBLE_FOR_REFUND,
    INTERNAL_SERVER_ERROR,
}
